const $=x=>document.getElementById(x),F=x=>(+x).toFixed(3),E=1e-9;let SHOWN=[];
function V(){return{L:+$("L").value,W:+$("W").value,BL:+$("BL").value,BW:+$("BW").value/100,G:+$("G").value/1000,K:+$("K").value/1000,MIN:+$("MIN").value/100,EDGE:+$("EDGE").value/100,MAX:+$("MAX").value}}
function rows(v){return Math.ceil((v.W+v.G)/(v.BW+v.G))}
function pack(ps,v){let bs=[];[...ps].sort((a,b)=>b.len-a.len).forEach(p=>{let bi=-1,br=1e99;bs.forEach((b,i)=>{let u=b.reduce((s,x)=>s+x.len,0)+Math.max(0,b.length-1)*v.K,rem=v.BL-u-(b.length?v.K:0)-p.len;if(rem>=-E&&rem<br){br=rem;bi=i}});bi<0?bs.push([p]):bs[bi].push(p)});return bs}
function variance(a){let m=a.reduce((s,x)=>s+x,0)/a.length;return a.reduce((s,x)=>s+(x-m)**2,0)/a.length}
function build(lines,v,label){let A=lines.filter((_,i)=>i%2===0),B=lines.filter((_,i)=>i%2===1);if(lines.length&&(!A.length||!B.length))return null;function ls(c){let p=[0,...c,v.L];return p.slice(1).map((x,i)=>+(x-p[i]).toFixed(3))}let LA=lines.length?ls(A):[v.L],LB=lines.length?ls(B):[v.L];if([...LA,...LB].some(x=>x<v.MIN-E||x>v.BL+E))return null;let R=rows(v),rs=[],ps=[];for(let r=0;r<R;r++){let Ls=r%2?LB:LA,type=r%2?"B":"A",rp=Ls.map((len,i)=>{let p={row:r+1,label:`${r+1}${String.fromCharCode(65+i)}`,len};ps.push(p);return p});rs.push({type,ps:rp})}let bins=pack(ps,v),d=R*v.L,g=lines.length?[lines[0],...lines.slice(1).map((x,i)=>x-lines[i]),v.L-lines.at(-1)]:[v.L];return{family:lines.length,label,lines,LA,LB,R,rs,ps,bins,util:100*d/(bins.length*v.BL),visual:variance(g),edge:lines.length?Math.abs(g[0]-g.at(-1)):0}}
function oneLine(v,x){let y=v.L-x,lines=[...new Set([+x.toFixed(3),+y.toFixed(3)])].sort((a,b)=>a-b),LA=[x,v.L-x],LB=[v.L-x,x];if([...LA,...LB].some(z=>z<v.MIN-E||z>v.BL+E))return null;let R=rows(v),rs=[],ps=[];for(let r=0;r<R;r++){let Ls=r%2?LB:LA,type=r%2?"B":"A",rp=Ls.map((len,i)=>{let p={row:r+1,label:`${r+1}${String.fromCharCode(65+i)}`,len:+len.toFixed(3)};ps.push(p);return p});rs.push({type,ps:rp})}let bins=pack(ps,v),d=R*v.L,g=[Math.min(x,y),Math.abs(y-x),Math.min(x,y)].filter(z=>z>E);return{family:1,label:"חיבור אחד בכל שורה",lines,LA,LB,R,rs,ps,bins,util:100*d/(bins.length*v.BL),visual:variance(g),edge:0}}
function candidates(v){let all=[];if(v.L<=v.BL+E){let q=build([],v,"ללא חיבורים");if(q)all.push(q)}for(let x=v.EDGE;x<=v.L/2+E;x+=.05){let q=oneLine(v,+x.toFixed(2));if(q)all.push(q)}for(let n=2;n<=v.MAX;n++){for(let shift=0;shift<=.6+E;shift+=.10){let first=v.EDGE+shift,last=v.L-v.EDGE-shift;if(last<=first)continue;let base=Array.from({length:n},(_,i)=>first+i*(last-first)/(n-1));for(let d=-.30;d<=.3001;d+=.10){let q=base.map((x,i)=>+(x+(i>0&&i<n-1?d*((i%2)?1:-1):0)).toFixed(2));if(q[0]<v.EDGE-E||v.L-q.at(-1)<v.EDGE-E||q.slice(1).some((x,i)=>x<=q[i]+E))continue;let z=build(q,v,`${n} קווי חיבור`);if(z)all.push(z)}}}let s=new Set();return all.filter(q=>{let k=q.lines.map(F).join("|")+"#"+q.LA.map(F)+"#"+q.LB.map(F);if(s.has(k))return false;s.add(k);return true})}
function valid(q,v){return !q.rs.some(r=>Math.abs(r.ps.reduce((s,x)=>s+x.len,0)-v.L)>.002)&&!q.ps.some(x=>x.len<v.MIN-E||x.len>v.BL+E)&&q.bins.every(b=>b.reduce((s,x)=>s+x.len,0)+Math.max(0,b.length-1)*v.K<=v.BL+.002)}
function select(P){let fam=new Map();P.forEach(q=>{if(!fam.has(q.family))fam.set(q.family,[]);fam.get(q.family).push(q)});let raw=[];for(let [f,a] of fam){raw.push([...a].sort((x,y)=>x.bins.length-y.bins.length||y.util-x.util)[0]);raw.push([...a].sort((x,y)=>x.visual-y.visual||x.bins.length-y.bins.length)[0])}let M=new Map();raw.filter(Boolean).forEach(q=>{let k=q.lines.map(F).join("|")+"#"+q.LA.map(F)+"#"+q.LB.map(F)+"#"+q.bins.length;if(!M.has(k))M.set(k,q)});return [...M.values()].sort((a,b)=>a.family-b.family||a.bins.length-b.bins.length||b.util-a.util).slice(0,16)}
function details(q,v){let kerf=q.bins.reduce((s,b)=>s+Math.max(0,b.length-1)*v.K,0),d=q.R*v.L,off=q.bins.map(b=>v.BL-b.reduce((s,x)=>s+x.len,0)-Math.max(0,b.length-1)*v.K),use=off.filter(x=>x>=v.MIN).reduce((s,x)=>s+x,0),waste=off.filter(x=>x<v.MIN).reduce((s,x)=>s+x,0),scr=q.bins.length*v.BL-d-kerf;return{use,waste,scr}}
function render(){let v=V(),P=candidates(v).filter(q=>valid(q,v));SHOWN=select(P);let h='<div class="card"><h2>חלופות חיפוי</h2><p class="muted">לחץ על חלופה כדי לפתוח את השרטוט ותוכנית החיתוך.</p></div>';SHOWN.forEach((q,i)=>{let d=details(q,v);h+=`<div class="card solution" onclick="toggleSol(${i})"><h2>חלופה ${i+1} — ${q.family===0?"ללא חיבורים":q.family+" קווי חיבור"}</h2><span class="tag">${q.bins.length} לוחות</span><span class="tag">${q.util.toFixed(2)}% ניצול</span><span class="tag">${q.lines.length} קווים נראים</span><span class="tag">שארית ${F(Math.max(0,d.scr))} מ׳</span><p><b>מיקומי החיבורים:</b> ${q.lines.length?q.lines.map(F).join(" / "):"אין"}<br><b>שורות A:</b> ${q.LA.map(F).join(" + ")}<br><b>שורות B:</b> ${q.LB.map(F).join(" + ")}</p><p><b>שארית שימושית:</b> ${F(d.use)} מ׳ · <b>שארית קצרה:</b> ${F(d.waste)} מ׳</p><div id="full${i}" class="hidden" onclick="event.stopPropagation()">${full(q,v,i)}</div></div>`});$("out").innerHTML=h}
function full(q,v,i){let h='<h3>שרטוט החיפוי</h3><div class="deck">';q.rs.forEach(r=>h+=`<div class="r">${r.ps.map(x=>`<div class="pc" style="width:${100*x.len/v.L}%">${r.type}${x.label}</div>`).join("")}</div>`);h+='</div><h3>תוכנית חיתוך</h3>';q.bins.forEach((b,j)=>{let k=Math.max(0,b.length-1)*v.K,rem=v.BL-b.reduce((s,x)=>s+x.len,0)-k;h+=`<b>לוח ${j+1}</b><div class="stock">${b.map(x=>`<div class="sp" style="width:${100*x.len/v.BL}%">${x.label} ${F(x.len)}</div>`).join("")}</div><small>${b.map(x=>`${F(x.len)} → ${x.label}`).join(" | ")} · חיתוך ${F(k)} · שארית ${F(Math.max(0,rem))}</small><br>`});h+=`<button onclick="chooseFrame(${i})">בחר חלופה זו לתכנון התשתית</button>`;return h}
window.toggleSol=i=>{let e=$("full"+i);e.classList.toggle("hidden")}
window.chooseFrame=i=>{drawFrame(SHOWN[i],V());$("frameOut").scrollIntoView({behavior:"smooth"})}
function drawFrame(q,v){let max=+$("JS").value/100;if(!(max>0))max=.4;let pos=[0],x=0;while(x+max<v.L-E){x+=max;pos.push(+x.toFixed(3))}if(Math.abs(pos.at(-1)-v.L)>E)pos.push(v.L);q.lines.forEach(x=>pos.push(x));pos=[...new Set(pos.map(x=>+x.toFixed(3)))].sort((a,b)=>a-b);let h=`<h3>תשתית מוצעת לחלופה שנבחרה</h3><p><b>${pos.length}</b> קווי תמיכה · מרווח מקסימלי שהוגדר: ${F(max)} מ׳.</p><div class="frame">`;pos.forEach(x=>{let joint=q.lines.some(j=>Math.abs(j-x)<.002);h+=`<div class="joist ${joint?'jointSupport':''}" style="left:${100*x/v.L}%"></div>`});h+=`</div><div class="legend">קו רגיל = קורת תשתית · קו כפול = תמיכה במיקום חיבור החיפוי</div><p><b>מיקומי קורות/תמיכות לאורך החיפוי:</b> ${pos.map(F).join(" / ")}</p><p class="muted">זהו Preview גיאומטרי: בגרסה הבאה נפריד בין קורה ראשית, קורת חיבור מקומית/Blocking, היקף, כמויות וחיתוכים.</p>`;$("frameOut").innerHTML=h}
$("go").onclick=render;["JS","JW","JEDGE"].forEach(id=>$(id).onchange=()=>{});render();