const $=x=>document.getElementById(x),F=x=>(+x).toFixed(3);
function V(){return{mode:$("mode").value,L:+$("L").value,W:+$("W").value,BL:+$("BL").value,BW:+$("BW").value,G:+$("G").value,K:+$("K").value,J:+$("J").value,MIN:+$("MIN").value,T:+$("T").value}}
function supports(v){let a=[0];for(let x=v.J;x<v.L;x+=v.J)a.push(+x.toFixed(3));a.push(v.L);return a}
function cuts(v,phase){let n=Math.ceil(v.L/v.BL),s=supports(v),c=[];for(let i=1;i<n;i++){let t=i*v.L/n+phase,x=s.filter(q=>q>=v.MIN&&q<=v.L-v.MIN).sort((a,b)=>Math.abs(a-t)-Math.abs(b-t))[0];if(x!=null&&!c.includes(x))c.push(x)}return c.sort((a,b)=>a-b)}
function make(v,a,b){let nr=Math.ceil((v.W+v.G)/(v.BW+v.G)),rows=[],all=[];for(let r=0;r<nr;r++){let c=cuts(v,r%2?b:a),z=[0,...c,v.L],ps=[];for(let i=1;i<z.length;i++){let len=+(z[i]-z[i-1]).toFixed(3);if(len>v.BL||len<v.MIN)return null;let p={row:r+1,label:`${r+1}${String.fromCharCode(64+i)}`,len};ps.push(p);all.push(p)}rows.push({row:r+1,c,ps})}
let bins=[];[...all].sort((a,b)=>b.len-a.len).forEach(p=>{let bi=-1,br=1e9;bins.forEach((q,i)=>{let u=q.reduce((s,x)=>s+x.len,0)+Math.max(0,q.length-1)*v.K,rem=v.BL-u-(q.length?v.K:0)-p.len;if(rem>=-1e-9&&rem<br){br=rem;bi=i}});bi<0?bins.push([p]):bins[bi].push(p)});
let util=100*all.reduce((s,p)=>s+p.len,0)/(bins.length*v.BL);return{nr,rows,bins,util}}
function search(v){let sh=[];for(let x=-v.J;x<=v.J+1e-9;x+=v.J/4)sh.push(x);let p=[];for(let a of sh)for(let b of sh){let q=make(v,a,b);if(q)p.push(q)}return p.sort((a,b)=>b.util-a.util||a.bins.length-b.bins.length)[0]}
function render(){let v=V(),p=search(v),o=$("out");if(!p){o.innerHTML='<div class="card warn">לא נמצאה פריסה חוקית.</div>';return}let ok=p.util>=v.T;
let h=`<div class="card"><h2>סיכום</h2><div class="${ok?'good':'warn'}">${ok?'🟢 יעד הושג':'🟠 היעד טרם הושג — בגרסת התכנון הבאה המנוע יבחן קורות חיבור נוספות'}</div><p>${p.nr} שורות · ${p.bins.length} לוחות · ניצול אורכי <b>${p.util.toFixed(1)}%</b></p></div><div class="card"><h2>תוכנית שורות</h2>`;
p.rows.forEach(r=>{h+=`<b>שורה ${r.row}</b><div class="row">${r.ps.map(x=>`<div class="p" style="width:${100*x.len/v.L}%">${x.label} ${F(x.len)}</div>`).join('')}</div><small>מידות: ${r.ps.map(x=>F(x.len)).join(' + ')} = ${F(v.L)} · חיבורים: ${r.c.map(F).join(' / ')}</small><br>`});h+='</div><div class="card"><h2>תוכנית חיתוך לפי לוח</h2>';
p.bins.forEach((b,i)=>{let used=b.reduce((s,x)=>s+x.len,0)+Math.max(0,b.length-1)*v.K,rem=v.BL-used;h+=`<h3>לוח #${i+1} — ${F(v.BL)} מ׳</h3><div class="bar">${b.map(x=>`<div class="p" style="width:${100*x.len/v.BL}%">${x.label} ${F(x.len)}</div>`).join('')}</div><p>${b.map(x=>`${F(x.len)} → שורה ${x.row}/${x.label}`).join(' | ')}<br><small>שארית אחרי kerf: ${F(rem)} מ׳</small></p>`});o.innerHTML=h+'</div>'} $("calc").onclick=render;render();